image: "python:3"
before_script:
  - pip3 install --user pyyaml selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar xvf geckodriver-v0.26.0-linux64.tar.gz
  - cp geckodriver /usr/bin
daily_duo:
  script:
    - ./ci.bash
