image: "selenium/node-firefox"
before_script:
  - sudo apt update && sudo apt install -y python3-pip
  - pip3 install --user pyyaml selenium
daily_duo:
  only:
    - schedules
  script:
    - python3 -u src/main/duobot.py -ci
