version: "3"
services:
  duobot:
    build: .
    command:
      - "duobot"
    volumes:
      - .:/app
    environment:
      - DISPLAY
      - DUOBOT_USERNAME
      - DUOBOT_PASSWORD
      - PYTHONUNBUFFERED=1
    network_mode: 'host' # dev only
